services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    networks:
      - chat-network

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge


#
#  nginx:
#    image: nginx:alpine
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#    depends_on:
#      - api
#      - web
#    networks:
#      - chat-network
#
#
